#SpringBoot多环境配置：可以选择激活哪一个环境配置
server:
  port: 8080
#  首页地址配置
  servlet:
    context-path: '/cjy'
Spring:
  mvc:
    format:
      date: dd/MM/yyyy
  thymeleaf:
    cache: false
  messages:
    basename: 'i18n.login'
#spring:
#  profiles:
#    active: test

---
server:
  port: 8081
spring:
  profiles: dev


---
server:
  port: 8082
spring:
  profiles: test



#person:
#  name: 张三${random.uuid}
#  age: ${random.int}
#  happy: true
#  birth: 2020/12/12
#  map: {k1: 1, K2: 2}
#  list:
#    - qqqq
#    - wwww
#    - eeee
#  dog:
#    name: 金毛
#    age: 3

